# Site
title:              "${ProjName}"
bio:                'This is a research page for publications and software created under Prof. Ganesh Gopalakrishnan’s guidance, for the ${ProjName} project.'
description:        "This is a research page for publications and software created under Prof. Ganesh Gopalakrishnan’s guidance, for the Comport ${ProjName} project."
baseurl:            "/comweb" # the subpath of your site, e.g. /blog #! will likely need replace me latter too
url:                "https://osterhoutan-UofU.github.io" # the base hostname & protocol for your site #! Replace me later
reference_bib_url:  "https://raw.githubusercontent.com/osterhoutan-UofU/comweb/less-bib-beta/site-content/references.bib"
pubs_bib_url:       "https://raw.githubusercontent.com/osterhoutan-UofU/comweb/less-bib-beta/site-content/pubs.bib"
locale:             en_US
destination:        "../docs" #? necessary for github pages to know where to find the site root.
# data_dir:           "../site-content/data" #/site-content/data


defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    author: anonymous
    # permalink: /comport/blog/:year/:month/:day/:title/ #! Fix me later

# Collections
collections:
  blog:
    collections_dir : ../site-content/blog
    permalink       : /:collection/:name
  people:
    collections_dir : ../site-content/info-pages/people
    permalink       : /:collection/:name
  education:
    collections_dir : ../site-content/info-pages/education
    permalink       : /:collection/:name
  software:
    collections_dir : ../site-content/info-pages/software
    permalink       : /:collection/:name


# Jekyll
# theme:              jekyll-theme-slate
# permalink:          /comport/blog/:year/:month/:day/:title/  #! Fix me later
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   default

# Social
analytics-id:       "default"
twitter:            default
facebook:           default
instagram:          default
# Probs replace this one with the org/project repo url
github:             default #! replace me with repo or org github url

# personal
location:           Salt Lake City, UT
phone:              (801) 581-8224
#email:              info@default.com


# notes about supported version id's are as of 2021-06-25 (see current status on https://pages.github.com/versions/) 
plugins:
  - jekyll-mentions   # YES (v1.6.0)
  - jekyll-sitemap    # YES (v1.4.0)
  - jekyll-feed       # YES (v0.15.1)
  - jekyll-gist       # YES (v0.15.1)
  - jekyll-paginate   # YES (v1.1.0)
  - jekyll-scholar    # ! NO !  (this one hurts as we use it's functionality a lot)
  # - jekyll-maps       # ! NO ! (but this only needs to generate one page so just move the gen content to includes)


paginate: 6
paginate_path: "/comport/blog/page:num/" #! Fix me later

jekyll-mentions:
  base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, docs, src, vendor, CNAME, LICENSE, Rakefile, old, scripts, par_site_tar.gz, fv_site_tar.gz, update_log.txt, .vscode, .mypy_cache, update_scripts]


maps:
  google:
      api_key: AIzaSyCUws1pOq7EnOvKS3niZxdzi3gVQajQhws

scholar:
  source: ../site-content
  bibliography: '**/*.bib'
  style: chicago-annotated-bibliography
  sort_by: year, month
  order: descending
  group_by: year
  group_order: descending
  bibliography_template: bib
  reference_tagname: div
  # bibliography_template: {{reference}}
